/* eslint-disable semi */
/* eslint-disable no-setter-return */
/* eslint-disable no-unused-vars */
/* eslint-disable eqeqeq */
/* eslint-disable curly */
// Generated by CoffeeScript 1.12.7
(function() {
    var XMLNodeList;

    module.exports = XMLNodeList = (function() {
        function XMLNodeList(nodes) {
            this.nodes = nodes;
        }

        Object.defineProperty(XMLNodeList.prototype, 'length', {
            get: function() {
                return this.nodes.length || 0;
            }
        });

        XMLNodeList.prototype.clone = function() {
            return this.nodes = null;
        };

        XMLNodeList.prototype.item = function(index) {
            return this.nodes[index] || null;
        };

        require('./internal').set('XMLNodeList', XMLNodeList);

        return XMLNodeList;

    })();

}).call(this);
